# Generated by Django 3.2.7 on 2021-11-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211028_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='DEFAULTVALUE', null=True, upload_to='images/'),
        ),
    ]
