# Generated by Django 3.2.9 on 2021-11-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_data',
            name='company_data1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='company_data2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company_data',
            name='company_image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
